# Generated by Django 6.0.3 on 2026-06-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NexBuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. electronics, gaming)', max_length=255, null=True),
        ),
    ]
